apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-monitoring-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-monitoring-operator
  template:
    metadata:
      labels:
        app: k8s-monitoring-operator
    spec:
      containers:
        - name: k8s-monitoring-operator
          image: k8s-monitoring-operator:latest
          imagePullPolicy: Never        # ← important! uses local image
          env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SLACK_WEBHOOK_URL
      serviceAccountName: k8s-monitoring-operator-sa